# Generated by Django 4.1.7 on 2023-04-20 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_banner_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 9, 36, 4, 663576)),
        ),
        migrations.AlterModelTable(
            name='banner',
            table='banners',
        ),
    ]
