# Generated by Django 4.1.7 on 2023-03-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_pic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
