# Generated by Django 4.1.7 on 2023-03-24 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_users_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'project_modules',
            },
        ),
        migrations.AddField(
            model_name='servicecategories',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.servicecategories'),
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('project_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.projectmodules')),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userroles')),
            ],
            options={
                'db_table': 'user_permissions',
            },
        ),
        migrations.AddConstraint(
            model_name='userpermissions',
            constraint=models.UniqueConstraint(fields=('user_role', 'project_module'), name='unique_permission'),
        ),
    ]
