# Generated by Django 4.1.7 on 2023-03-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_projectmodules_servicecategories_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategories',
            old_name='parent',
            new_name='parent_category',
        ),
    ]
