# Generated by Django 4.1.7 on 2023-03-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_parent_servicecategories_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='fcm_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
