# Generated by Django 4.1.7 on 2023-03-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_users_fcm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='country_code',
            field=models.IntegerField(default=1),
        ),
    ]
