# Generated by Django 4.1.7 on 2023-03-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_users_country_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='fcm_id',
            new_name='fcm_token',
        ),
    ]
