# Generated by Django 4.1.7 on 2023-04-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_users_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraddress',
            unique_together={('street_address', 'house_number', 'city', 'state', 'zip_code')},
        ),
    ]
