# Generated by Django 4.1.7 on 2023-04-08 09:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_providers_service_category_and_more'),
        ('services', '0002_servicecart_show_in_cart_servicebooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 8, 9, 32, 26, 709766, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.CASCADE, to='login.users'),
        ),
        migrations.AddField(
            model_name='services',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='servicebooking',
            unique_together={('user', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='servicecart',
            unique_together={('user', 'service')},
        ),
    ]
