# Generated by Django 4.1.7 on 2023-04-18 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_servicecategories_image_alter_servicecategories_name'),
        ('services', '0003_services_created_at_services_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.CASCADE, to='login.providers'),
        ),
    ]
