# Generated by Django 4.1.7 on 2023-04-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_services_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.CharField(default='provider_driving_licenses/back.png', max_length=200),
        ),
    ]
